### ISSUE TITLE
Scaling of portrait mode videos

### ISSUE THREAD

**Issue by twilightDD** [starkdmi/MediaToolSwift#2]
If I try to scale a video in portrait mode, the resolution of the encoded video is a little bit weird.

I import a video with a resolution of 2160x3840 and set 1280x720 as the target resolution. My expectation is that the encoded video has a resolution of 720x1280. Instead I get 405x720.

-------

In the `initVideo()` method of `Video.swift` there's a check for resolution changes.

```
if let size = videoSettings.size,
   videoSize.width > size.width || videoSize.height > size.height {
      let rect = AVMakeRect(aspectRatio: videoSize, insideRect: CGRect(origin: CGPoint.zero, size: size))
      videoSize = rect.size
   }
```

-------

My workaround: Right before the code above I switch the dimension of `videoSettings.size`

```
var videoSettings = videoSettings
if let size = videoSettings.size,
    videoSize.width < videoSize.height {
    videoSettings.size = CGSize(width: size.height, height: size.width)
}

```

Result: I import a video with a resolution of 2160x3840 and set 1280x720 as the target resolution. The encoded video has a resolution of 720x1280.

**Comment by starkdmi** [comment]
Resolution is based on the size-to-fit with aspect ratio concept. That allows to work with both landscape and portrait videos using the same bounds.

Which means instead of 1280x720 in your case you just need to specify maximum for both width and height - 1280x1280. 

The `CGSize` extension contains some of predefined squared resolutions as well - [link](https://github.com/starkdmi/MediaToolSwift/blob/5ff430000d623af3de7e89024ec1d57c6ecacc37/Sources/Extensions/CGSize%2BExtensions.swift#L4).

**Comment by twilightDD** [comment]
Ah! Thank you. A nice example of "your holding it wrong" :-)
